### ISSUE TITLE
Too-fast scrolling in RA

### ISSUE THREAD

**Issue by elliotcm** [hifi/cnc-ddraw#1]
Hi there,

I know you guys reported in your changelogs that you've fixed a bug like this, but I'm still getting near-instant scrolling in RA with the latest build of the DDL from your website under Windows 7.

Any ideas?

Thanks.

**Comment by hifi** [comment]
Hi,

Enable backbuffer in rasetup.exe and make sure you have maxfps set to some sane value in ddarw.ini.

**Comment by elliotcm** [comment]
I already had backbuffer set, but setting maxfps to -1 sorted me out.

Many thanks!
